language: php

php:
  - 7.2

script:
  - composer install
  - ./vendor/bin/phpunit -v --coverage-text

matrix:
  include:
    - os: linux
      sudo: required
      dist: precise
      php: 5.3
  allow_failures:
    - php: hhvm
